# Global Settings
title: Technology
author: Paul Dürnberger
description:
  I write about Linux and Ubuntu, and the FOSS tools available to photographers

keywords:
  atom, bootstrap, css, html, foss, github, git, jekyll, linux, markdown, photography, technology, ubuntu

strapline: Linux and Photography

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

include: ['_pages']

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Excerpt Separator
excerpt_separator: <!--more-->

# Files to Ignore on Build
keep_files: ['.jpg', '.jpeg', '.gif', '.pdf']

# Exclude from Processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
